# Generated by Django 4.2 on 2024-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='主題')),
                ('message', models.TextField(verbose_name='留言訊息')),
                ('from_email', models.EmailField(default='georgiawang5332@gmail.com', editable=False, max_length=254, verbose_name='來自郵件')),
                ('to_email', models.EmailField(max_length=254, verbose_name='員工郵件帳號')),
            ],
            options={
                'verbose_name': '寄發郵件',
                'verbose_name_plural': '寄發郵件',
            },
        ),
    ]
