"""
Django settings for erpProject project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-25kj!mcjp_-p23$d+$b9vz(pi!6(r6c_b5i)e^cfpc-o_)inlw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # 通常是 587 或 465
EMAIL_USE_TLS = True  # 或 False，取決於您的 SMTP 服務器
EMAIL_HOST_USER = 'georgiawang5332@gmail.com'
EMAIL_HOST_PASSWORD = 'spotksfpejpmbndp'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 'background_task',
    # 'django_crontab', #信件自動更新上傳到前端
    # 'django_apscheduler',#套件支持在Windows上定期運行Django任務
    'invitationCard',
    'calendarapp',
    'accounts',
    'dashboard',
    'website',
# 
    'BudgetSheet',
    'PreparationFlowChart',
    'InviteSendForm',
    'CeremonyWeddingChecklist',
    'DayItemList',
    'DayProcess',
    'CarAllocation',
    'BanquetStaffList',
    'SeatingAssignments',
# 
    'sendEmail',
    'PersonnelAddressBook',
    'Resume',

    # 套版
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erpProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'PersonnelAddressBook.context_processors.email_count',
                'PersonnelAddressBook.context_processors.notification_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'erpProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'OPTIONS': {
        'charset': 'utf8mb4',
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'# 設定為你當地的時區

USE_I18N = True
# 這個設置確保 Django 使用本地化格式來顯示日期和時間。
USE_L10N = True
# 這個設置關閉了 Django 的時區支持，這意味著 Django 將會假設所有的時間都是本地時間而不是 UTC。
USE_TZ = True# 允許使用時區


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# 收集靜態文件的目錄
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 靜態文件的其他目錄
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 靜態檔案和媒體檔案配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/afterlogin'

# Celery 設定
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # 或者你選擇的其他 broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # 使用相同的 Redis 地址作為 backend

# 可選：其他 Celery 設定
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Taipei'