# Generated by Django 4.2.7 on 2024-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Joined加入日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active積極的'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff status員工狀況'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated最後更新'),
        ),
    ]
