# Generated by Django 4.2.7 on 2024-08-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='類別名稱')),
            ],
            options={
                'verbose_name': '類別',
                'verbose_name_plural': '類別',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='貨幣名稱')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='貨幣代碼')),
                ('symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='貨幣符號')),
            ],
            options={
                'verbose_name': '貨幣',
                'verbose_name_plural': '貨幣',
            },
        ),
        migrations.CreateModel(
            name='BudgetSheetModel',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項目編號')),
                ('expenditure_items', models.CharField(max_length=200, verbose_name='支出項目')),
                ('estimated_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='預計數量')),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='預計單價')),
                ('remark_one', models.TextField(verbose_name='備註1')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='實際數量')),
                ('actual_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='實際單價')),
                ('payer', models.CharField(max_length=200, verbose_name='付款人')),
                ('remark_two', models.TextField(verbose_name='備註2')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetSheet.category', verbose_name='類別')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BudgetSheet.currency', verbose_name='貨幣')),
            ],
            options={
                'verbose_name': '婚禮預算表',
                'verbose_name_plural': '婚禮預算表',
                'ordering': ['-expenditure_items'],
            },
        ),
    ]
