# Generated by Django 5.0.6 on 2024-06-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetSheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsheetmodel',
            name='estimated_expenses',
        ),
        migrations.RemoveField(
            model_name='budgetsheetmodel',
            name='is_selected_for_payment',
        ),
        migrations.RemoveField(
            model_name='budgetsheetmodel',
            name='paid',
        ),
    ]
