# Generated by Django 5.0.6 on 2024-07-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetSheet', '0002_remove_budgetsheetmodel_estimated_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetsheetmodel',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='實際數量'),
        ),
        migrations.AlterField(
            model_name='budgetsheetmodel',
            name='actual_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='實際單價'),
        ),
        migrations.AlterField(
            model_name='budgetsheetmodel',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BudgetSheet.currency', verbose_name='貨幣'),
        ),
        migrations.AlterField(
            model_name='budgetsheetmodel',
            name='estimated_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='預計數量'),
        ),
        migrations.AlterField(
            model_name='budgetsheetmodel',
            name='estimated_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='預計單價'),
        ),
    ]
